/** @type {import('tailwindcss').Config} */
// Tokens come straight from the GateLog design system (DESIGN.md / the Stitch
// export's tailwind-config), so class names in the pages match the designs.
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#acedff',
        'tertiary-fixed': '#ffddb8',
        'surface-variant': '#31353e',
        'surface-dim': '#0f131c',
        'surface-container': '#1c2028',
        'on-tertiary-fixed-variant': '#653e00',
        'outline-variant': '#3d494c',
        'on-primary-fixed-variant': '#004e5c',
        'on-error': '#690005',
        'inverse-on-surface': '#2c3039',
        'surface-tint': '#4cd7f6',
        'on-secondary-fixed': '#002113',
        'on-primary': '#003640',
        'surface-bright': '#353942',
        background: '#0f131c',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary': '#472a00',
        outline: '#869397',
        'secondary-container': '#00a572',
        'secondary-fixed': '#6ffbbe',
        'on-primary-container': '#00424f',
        'on-surface-variant': '#bcc9cd',
        'on-secondary-container': '#00311f',
        'inverse-surface': '#dfe2ee',
        'on-tertiary-fixed': '#2a1700',
        surface: '#0f131c',
        'on-secondary': '#003824',
        'on-primary-fixed': '#001f26',
        'surface-container-low': '#181c24',
        'on-tertiary-container': '#563400',
        'on-surface': '#dfe2ee',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-container-highest': '#31353e',
        'surface-container-high': '#262a33',
        'on-background': '#dfe2ee',
        tertiary: '#ffb95f',
        'primary-container': '#06b6d4',
        primary: '#4cd7f6',
        'primary-fixed-dim': '#4cd7f6',
        'tertiary-container': '#e79400',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#4edea3',
        'error-container': '#93000a',
        secondary: '#4edea3',
        error: '#ffb4ab',
        'surface-container-lowest': '#0a0e16',
        'inverse-primary': '#00687a',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        'space-md': '1rem',
        margin: '2rem',
        'gutter-mobile': '0.75rem',
        gutter: '1.25rem',
        'margin-mobile': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'headline-lg': ['Inter Variable', 'Inter', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Inter Variable', 'Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter Variable', 'Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter Variable', 'Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter Variable', 'Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter Variable', 'Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['Inter Variable', 'Inter', 'system-ui', 'sans-serif'],
        'label-caps': ['Inter Variable', 'Inter', 'system-ui', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'code-tabular': ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'code-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'code-tabular': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
